/**
 * Action Types
 */

// Set token
export const SET_TOKEN = "SET_TOKEN";

// Fetch user from token
export const FETCH_USER_ASYNC = "FETCH_USER_ASYNC";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

// Fetch recent runs
export const FETCH_RECENT_RUNS_ASYNC = "FETCH_RECENT_RUNS_ASYNC";
export const FETCH_RECENT_RUNS_SUCCESS = "FETCH_RECENT_RUNS_SUCCESS";
export const FETCH_RECENT_RUNS_FAILURE = "FETCH_RECENT_RUNS_FAILURE";

// Fetch recent samples
export const FETCH_RECENT_SAMPLES_ASYNC = "FETCH_RECENT_SAMPLES_ASYNC";
export const FETCH_RECENT_SAMPLES_SUCCESS = "FETCH_RECENT_SAMPLES_SUCCESS";
export const FETCH_RECENT_SAMPLES_FAILURE = "FETCH_RECENT_SAMPLES_FAILURE";

// Fetch filters
export const FETCH_FILTERS_ASYNC = "FETCH_FILTERS_ASYNC";
export const FETCH_FILTERS_SUCCESS = "FETCH_FILTERS_SUCCESS";
export const FETCH_FILTERS_FAILURE = "FETCH_FILTERS_FAILURE";

// Download samples
export const DOWNLOAD_SAMPLES_ASYNC = "DOWNLOAD_SAMPLES_ASYNC";
export const DOWNLOAD_SAMPLES_SUCCESS = "DOWNLOAD_SAMPLES_SUCCESS";
export const DOWNLOAD_SAMPLES_FAILURE = "DOWNLOAD_SAMPLES_FAILURE";

// Fetch related samples
export const FETCH_RELATED_SAMPLES_ASYNC = "FETCH_RELATED_SAMPLES_ASYNC";
export const FETCH_RELATED_SAMPLES_SUCCESS = "FETCH_RELATED_SAMPLES_SUCCESS";
export const FETCH_RELATED_SAMPLES_FAILURE = "FETCH_RELATED_SAMPLES_FAILURE";

// Fetch phylo tree
export const FETCH_PHYLOTREE_ASYNC = "FETCH_PHYLOTREE_ASYNC";
export const FETCH_PHYLOTREE_SUCCESS = "FETCH_PHYLOTREE_SUCCESS";
export const FETCH_PHYLOTREE_FAILURE = "FETCH_PHYLOTREE_FAILURE";

// Fetch sample details
export const FETCH_SAMPLE_DETAILS_ASYNC = "FETCH_SAMPLE_DETAILS_ASYNC";
export const FETCH_SAMPLE_DETAILS_SUCCESS = "FETCH_SAMPLE_DETAILS_SUCCESS";
export const FETCH_SAMPLE_DETAILS_FAILURE = "FETCH_SAMPLE_DETAILS_FAILURE";

// Set current values
export const SET_CURRENT_RUN = "SET_CURRENT_RUN";
export const SET_CURRENT_SAMPLE = "SET_CURRENT_SAMPLE";
export const SET_CURRENT_PHYLO = "SET_CURRENT_PHYLO";
export const SET_FEATURE_VIEWER = "SET_FEATURE_VIEWER";

// Fetch sample details
export const FETCH_FEATURE_VIEWER_ASYNC = "FETCH_FEATURE_VIEWER_ASYNC";
export const FETCH_FEATURE_VIEWER_SUCCESS = "FETCH_FEATURE_VIEWER_SUCCESS";
export const FETCH_FEATURE_VIEWER_FAILURE = "FETCH_FEATURE_VIEWER_FAILURE";

// Fetch analytics data
export const FETCH_ANALYTICS_ASYNC = "FETCH_ANALYTICS_ASYNC";
export const FETCH_ANALYTICS_SUCCESS = "FETCH_ANALYTICS_SUCCESS";
export const FETCH_ANALYTICS_FAILURE = "FETCH_ANALYTICS_FAILURE";

// Set selected filters
export const SET_SELECTED_FILTERS = "SET_SELECTED_FILTERS";

// Fetch samples from file
export const FETCH_SAMPLES_FROM_FILE_ASYNC = "FETCH_SAMPLES_FROM_FILE_ASYNC";
export const FETCH_SAMPLES_FROM_FILE_SUCCESS =
  "FETCH_SAMPLES_FROM_FILE_SUCCESS";
export const FETCH_SAMPLES_FROM_FILE_FAILURE =
  "FETCH_SAMPLES_FROM_FILE_FAILURE";
