const colors = {
  serogroupingGenes: [
    { name: 'ctrA', color: '#d10000' },
    { name: 'cslA', color: '#9bc6e8' },
    { name: 'ctrB', color: '#ff6622' },
    { name: 'ctrC', color: '#ffda21' },
    { name: 'ctrD', color: '#33dd00' },
    { name: 'ctrE', color: '#758df9' },
    { name: 'ctrF', color: '#9380ba' },
    { name: 'tex', color: '#4dffa6' },
    { name: 'cszA', color: '#e19be8' },
    { name: 'cshA', color: '#e8e09b' },
    { name: 'cnl', color: '#ff8800' },
    { name: 'cssB', color: '#f27b48' },
    { name: 'cssC', color: '#ddb442' },
    { name: 'csc', color: '#d8d56e' },
    { name: 'cssA', color: '#8c2a2a' },
    { name: 'csb', color: '#d17047' },
    { name: 'csaA', color: '#8c2a2a' },
    { name: 'csaB', color: '#33dd00' },
    { name: 'csaC', color: '#4dffa6' },
    { name: 'csaD', color: '#e8e09b' },
    { name: 'cseA', color: '#33dd00' },
    { name: 'cseB', color: '#758df9' },
    { name: 'cseC', color: '#9380ba' },
    { name: 'cseD', color: '#4dffa6' },
    { name: 'cseE', color: '#e19be8' },
    { name: 'cseG', color: '#e8e09b' },
    { name: 'cshB', color: '#d8d56e' },
    { name: 'cslA', color: '#66b2b2' },
    { name: 'cslB', color: '#008080' },
    { name: 'cslC', color: '#005555' },
    { name: 'csw', color: '#70947b' },
    { name: 'csxA', color: '#3a6965' },
    { name: 'csxB', color: '#202c45' },
    { name: 'csxC', color: '#d0c774' },
    { name: 'csy', color: '#c79d68' },
    { name: 'cszB', color: '#9c7171' },
    { name: 'cszC', color: '#ba8888' },
    { name: 'cszD', color: '#ce9c9c' },
  ],
  serotypingGenes: [
    { name: 'acs1', color: '#8c2a2a' },
    { name: 'acs2', color: '#33dd00' },
    { name: 'acs3', color: '#4dffa6' },
    { name: 'acs4', color: '#e8e09b' },
    { name: 'bcs1', color: '#8c2a2a' },
    { name: 'bcs2', color: '#d17047' },
    { name: 'bcs3', color: '#d10000' },
    { name: 'bcs4', color: '#758df9' },
    { name: 'bexA', color: '#d10000' },
    { name: 'bexB', color: '#9bc6e8' },
    { name: 'bexC', color: '#ff6622' },
    { name: 'bexD', color: '#ffda21' },
    { name: 'ccs1', color: '#f2946b' },
    { name: 'ccs2', color: '#fdb965' },
    { name: 'ccs3', color: '#f9df74' },
    { name: 'ccs4', color: '#f8ff89' },
    { name: 'dcs1', color: '#917c9b' },
    { name: 'dcs2', color: '#9b7b95' },
    { name: 'dcs3', color: '826f8b#' },
    { name: 'dcs4', color: '#99ada7' },
    { name: 'dcs5', color: '#a79aad' },
    { name: 'ecs1', color: '#33dd00' },
    { name: 'ecs2', color: '#758df9' },
    { name: 'ecs3', color: '#9380ba' },
    { name: 'ecs4', color: '#4dffa6' },
    { name: 'ecs5', color: '#e19be8' },
    { name: 'ecs6', color: '#e8e09b' },
    { name: 'ecs7', color: '#ff8800' },
    { name: 'ecs8', color: '#f27b48' },
    { name: 'fcs1', color: '#66b2b2' },
    { name: 'fcs2', color: '#008080' },
    { name: 'fcs3', color: '#005555' },
    { name: 'hcsA', color: '#ddb442' },
    { name: 'hcsB', color: '#d8d56e' },
  ],
};

module.exports = { colors };
